DROP TABLE IF EXISTS member;

CREATE TABLE member
(
   `MEMBER_ID`         MEDIUMINT      NOT NULL AUTO_INCREMENT,
   `LOGIN_ID`          VARCHAR(30)    NOT NULL COMMENT '用户ID',
   `ENCODED_PASSWORD`  VARCHAR(256) COMMENT '暗号化密码',
   `NICK_NAME`         VARCHAR(256) COMMENT '昵称',
   `EMAIL`             VARCHAR(256) COMMENT '邮箱',
   `BIRTHDAY`          VARCHAR(8) COMMENT '生日',
   `GENDER`            VARCHAR(1) COMMENT '性别',
   `TELPHONE`          VARCHAR(100) COMMENT '电话',
   `RANK`              INT COMMENT '积分',
   `ICON`              BLOB COMMENT '头像',
   `ADMIN_ROLE`        VARCHAR(20) COMMENT '創建日時',
   `DEL_FLG`           INT            DEFAULT 1,
   `CREATE_NAME`       VARCHAR(30)    DEFAULT 'SYS01' COMMENT '創建者名',
   `CREATE_DATE`       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '創建日時',
   `UPDATE_NAME`       VARCHAR(30)    DEFAULT 'SY＠S01' COMMENT '更新者名',
   `UPDATE_DATE`       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新日時',
   PRIMARY KEY (`MEMBER_ID`)
)
ENGINE=InnoDB;

CREATE UNIQUE INDEX `LOGINID`
   ON member (`LOGIN_ID` ASC);

